#!/usr/bin/env node

import {
  chmodSync,
  existsSync,
  readFileSync,
  renameSync,
  writeFileSync,
} from "node:fs";
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { Writable } from "node:stream";

const agentHostDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = resolve(agentHostDir, "..");
const configPath = resolve(
  process.env.AGENT_SETUP_CONFIG_PATH || resolve(repositoryRoot, ".env.agent"),
);
const workspaceRoot = resolve(
  process.env.AGENT_SETUP_WORKSPACE || repositoryRoot,
);
const completionMarker = resolve(agentHostDir, ".setup-complete");
const configureOnly = process.argv.includes("--configure-only");

async function main() {
  assertNodeVersion();
  const existingText = existsSync(configPath)
    ? readFileSync(configPath, "utf8")
    : "# Generated by ./agent setup. This file contains secrets; do not commit it.\n";
  const existing = parseEnv(existingText);
  const values = await collectValues(existing);
  writeConfig(existingText, values);
  console.log(`\nSaved private Agent configuration to ${configPath}`);

  if (!configureOnly) {
    run(npmCommand(), ["ci", "--ignore-scripts"]);
    run(process.execPath, ["scripts/patch-pi-brace-expansion.mjs"]);
    run(process.execPath, ["scripts/patch-pi-brace-expansion.mjs", "--check"]);
    run(npmCommand(), ["run", "build"]);
    run(process.execPath, ["dist/src/cli.js", "doctor"]);
    writeFileSync(completionMarker, `${new Date().toISOString()}\n`, {
      encoding: "utf8",
      mode: 0o600,
    });
    chmodSync(completionMarker, 0o600);
    console.log("\nAgent setup is complete. Run ./agent to open the Pi TUI.");
  }
}

async function collectValues(existingValues) {
  const keys = [
    {
      key: "AGENT_HUB_URL",
      label: "Hub URL",
      validate: (value) => validateUrl(value, "Hub URL"),
    },
    {
      key: "AGENT_HUB_TOKEN",
      label: "Hub token",
      secret: true,
      validate: (value) => {
        if (value.length < 24) throw new Error("Hub token must contain at least 24 characters");
      },
    },
    {
      key: "AGENT_REMOTE_BASE_URL",
      label: "OpenAI-compatible model URL",
      validate: (value) => validateUrl(value, "Model URL"),
    },
    {
      key: "AGENT_REMOTE_MODEL",
      label: "Model ID",
    },
    {
      key: "AGENT_REMOTE_API_KEY",
      label: "Model API key",
      secret: true,
    },
  ];
  const values = {};
  const interactive = Boolean(stdin.isTTY && stdout.isTTY);
  const mutedOutput = new MutedOutput();
  const terminal = interactive
    ? createInterface({ input: stdin, output: mutedOutput, terminal: true })
    : undefined;
  try {
    for (const item of keys) {
      const current = process.env[item.key]?.trim() || existingValues[item.key] || "";
      let value = current;
      if (interactive) {
        value = item.secret
          ? await askSecret(terminal, mutedOutput, item.label, current)
          : await askVisible(terminal, item.label, current || item.fallback || "");
      }
      if (!value || looksLikePlaceholder(value)) {
        throw new Error(`${item.label} is required`);
      }
      rejectUnsupportedEnvCharacters(item.label, value);
      item.validate?.(value);
      values[item.key] = value;
    }
  } finally {
    terminal?.close();
  }
  values.AGENT_WORKSPACE_ROOT = workspaceRoot;
  return values;
}

async function askVisible(terminal, label, current) {
  const answer = (await terminal.question(`${label} [${current}]: `)).trim();
  return answer || current;
}

async function askSecret(terminal, output, label, current) {
  stdout.write(`${label}${current ? " [configured; Enter keeps it]" : ""}: `);
  output.muted = true;
  const answer = (await terminal.question("")).trim();
  output.muted = false;
  stdout.write("\n");
  return answer || current;
}

class MutedOutput extends Writable {
  muted = false;

  _write(chunk, encoding, callback) {
    if (!this.muted) stdout.write(chunk, encoding);
    callback();
  }
}

function parseEnv(text) {
  const values = {};
  for (const rawLine of text.split(/\r?\n/u)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#") || !line.includes("=")) continue;
    const separator = line.indexOf("=");
    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

function writeConfig(original, values) {
  const lines = original.split(/\r?\n/u);
  const remaining = new Map(Object.entries(values));
  const next = lines.map((line) => {
    const match = line.match(/^\s*([A-Z][A-Z0-9_]*)\s*=/u);
    if (!match || !remaining.has(match[1])) return line;
    const key = match[1];
    const value = remaining.get(key);
    remaining.delete(key);
    return `${key}=${dotenvValue(value)}`;
  });
  if (remaining.size) {
    if (next.at(-1)?.trim()) next.push("");
    for (const [key, value] of remaining) next.push(`${key}=${dotenvValue(value)}`);
  }
  const temporary = `${configPath}.${process.pid}.tmp`;
  writeFileSync(temporary, `${next.join("\n").replace(/\n+$/u, "")}\n`, {
    encoding: "utf8",
    mode: 0o600,
  });
  chmodSync(temporary, 0o600);
  renameSync(temporary, configPath);
}

function dotenvValue(value) {
  if (!value.includes('"')) return `"${value}"`;
  if (!value.includes("'")) return `'${value}'`;
  throw new Error("Configuration values cannot contain both quote styles");
}

function validateUrl(value, label) {
  let parsed;
  try {
    parsed = new URL(value);
  } catch {
    throw new Error(`${label} must be a valid URL`);
  }
  if (!["http:", "https:"].includes(parsed.protocol)) {
    throw new Error(`${label} must use HTTP or HTTPS`);
  }
}

function rejectUnsupportedEnvCharacters(label, value) {
  if (/[\r\n]/u.test(value)) throw new Error(`${label} cannot contain newlines`);
}

function looksLikePlaceholder(value) {
  return (
    value.startsWith("replace-with-") ||
    value === "your-model-id" ||
    value.includes("example.com")
  );
}

function assertNodeVersion() {
  const [major, minor] = process.versions.node.split(".").map(Number);
  if (major < 22 || (major === 22 && minor < 19)) {
    throw new Error(`Node.js 22.19 or newer is required; found ${process.versions.node}`);
  }
}

function npmCommand() {
  return process.platform === "win32" ? "npm.cmd" : "npm";
}

function run(command, args) {
  console.log(`\n> ${command} ${args.join(" ")}`);
  const result = spawnSync(command, args, {
    cwd: agentHostDir,
    env: process.env,
    stdio: "inherit",
  });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
}

main().catch((error) => {
  console.error(`\nSetup failed: ${error instanceof Error ? error.message : String(error)}`);
  process.exitCode = 1;
});
