#!/usr/bin/env node

import {
  chmodSync,
  existsSync,
  readFileSync,
  renameSync,
  writeFileSync,
} from "node:fs";
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { userInfo } from "node:os";
import { Writable } from "node:stream";

const agentHostDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = resolve(agentHostDir, "..");
const configPath = resolve(
  process.env.AGENT_SETUP_CONFIG_PATH || resolve(repositoryRoot, ".env.agent"),
);
const workspaceRoot = resolve(
  process.env.AGENT_SETUP_WORKSPACE || repositoryRoot,
);
const completionMarker = resolve(agentHostDir, ".setup-complete");
const configureOnly = process.argv.includes("--configure-only");

async function main() {
  assertNodeVersion();
  if (!configureOnly) {
    run(npmCommand(), ["ci", "--ignore-scripts"]);
    run(process.execPath, ["scripts/patch-pi-brace-expansion.mjs"]);
    run(process.execPath, ["scripts/patch-pi-brace-expansion.mjs", "--check"]);
  }
  const existingText = existsSync(configPath)
    ? normalizeConfigHeader(readFileSync(configPath, "utf8"))
    : "# Generated by AgentSociety setup. Secret values live in the system credential store.\n";
  const existing = parseEnv(existingText);
  const credentials = await createCredentialStore();
  const values = await collectValues(existing, credentials);
  writeConfig(existingText, values);
  console.log(`\nSaved non-secret Agent configuration to ${configPath}`);

  if (!configureOnly) {
    run(npmCommand(), ["run", "build"]);
    run(process.execPath, ["dist/src/cli.js", "doctor"]);
    writeFileSync(completionMarker, `${new Date().toISOString()}\n`, {
      encoding: "utf8",
      mode: 0o600,
    });
    chmodSync(completionMarker, 0o600);
    console.log("\nAgent setup is complete. Run ./agent to open the Pi TUI.");
  }
}

function normalizeConfigHeader(text) {
  return text.replace(
    "# Generated by AgentSociety setup. This file contains secrets; do not commit it.",
    "# Generated by AgentSociety setup. Secret values live in the system credential store.",
  );
}

async function collectValues(existingValues, credentials) {
  const keys = [
    {
      key: "AGENT_REMOTE_BASE_URL",
      label: "OpenAI-compatible model URL",
      validate: (value) => validateUrl(value, "Model URL"),
    },
    {
      key: "AGENT_REMOTE_MODEL",
      label: "Model ID",
    },
  ];
  const values = {};
  const interactive = Boolean(stdin.isTTY && stdout.isTTY);
  const mutedOutput = new MutedOutput();
  const terminal = interactive
    ? createInterface({ input: stdin, output: mutedOutput, terminal: true })
    : undefined;
  try {
    for (const item of keys) {
      const current = process.env[item.key]?.trim() || existingValues[item.key] || "";
      let value = current;
      if (interactive) {
        value = await askVisible(terminal, item.label, current);
      }
      if (!value || looksLikePlaceholder(value)) {
        throw new Error(`${item.label} is required`);
      }
      rejectUnsupportedEnvCharacters(item.label, value);
      item.validate?.(value);
      values[item.key] = value;
    }

    const modelCredential = credentialReference(existingValues, "model");
    const configuredModelKey =
      process.env.AGENT_REMOTE_API_KEY?.trim() ||
      process.env.LLM_API_KEY?.trim() ||
      existingValues.AGENT_REMOTE_API_KEY ||
      existingValues.LLM_API_KEY ||
      credentials.read(modelCredential, "remote model") ||
      "";
    const modelApiKey = interactive
      ? await askSecret(
          terminal,
          mutedOutput,
          "Model API key",
          configuredModelKey,
        )
      : configuredModelKey;
    if (!modelApiKey || looksLikePlaceholder(modelApiKey)) {
      throw new Error("Model API key is required");
    }
    rejectUnsupportedEnvCharacters("Model API key", modelApiKey);
    credentials.write(modelCredential, modelApiKey, "remote model");
    values.AGENT_REMOTE_API_KEY = null;
    values.LLM_API_KEY = null;
    values.AGENT_REMOTE_API_KEY_KEYCHAIN_SERVICE = null;
    values.AGENT_REMOTE_API_KEY_KEYCHAIN_ACCOUNT = null;
    values.AGENT_REMOTE_API_KEY_CREDENTIAL_SERVICE = modelCredential.service;
    values.AGENT_REMOTE_API_KEY_CREDENTIAL_ACCOUNT = modelCredential.account;

    const configuredHubUrl =
      process.env.AGENT_HUB_URL?.trim() || existingValues.AGENT_HUB_URL || "";
    let hubUrl = configuredHubUrl;
    if (interactive) {
      const hint = configuredHubUrl
        ? `${configuredHubUrl}; Enter keeps it, - disables`
        : "optional; Enter skips";
      const answer = (await terminal.question(`Hub URL [${hint}]: `)).trim();
      hubUrl = answer === "-" ? "" : answer || configuredHubUrl;
    }
    const hubCredential = credentialReference(existingValues, "hub");
    const configuredHubToken =
      process.env.AGENT_HUB_TOKEN?.trim() ||
      existingValues.AGENT_HUB_TOKEN ||
      (hubUrl ? credentials.read(hubCredential, "Hub") : "") ||
      "";
    if (hubUrl) {
      rejectUnsupportedEnvCharacters("Hub URL", hubUrl);
      if (looksLikePlaceholder(hubUrl)) throw new Error("Hub URL is required");
      validateUrl(hubUrl, "Hub URL");
      const hubToken = interactive
        ? await askSecret(terminal, mutedOutput, "Hub token", configuredHubToken)
        : configuredHubToken;
      if (!hubToken || looksLikePlaceholder(hubToken)) {
        throw new Error("Hub token is required when Hub URL is configured");
      }
      if (hubToken.length < 24) {
        throw new Error("Hub token must contain at least 24 characters");
      }
      rejectUnsupportedEnvCharacters("Hub token", hubToken);
      credentials.write(hubCredential, hubToken, "Hub");
      values.AGENT_HUB_URL = hubUrl;
      values.AGENT_HUB_TOKEN = null;
      values.AGENT_HUB_TOKEN_KEYCHAIN_SERVICE = null;
      values.AGENT_HUB_TOKEN_KEYCHAIN_ACCOUNT = null;
      values.AGENT_HUB_TOKEN_CREDENTIAL_SERVICE = hubCredential.service;
      values.AGENT_HUB_TOKEN_CREDENTIAL_ACCOUNT = hubCredential.account;
    } else {
      const directlyConfiguredHubToken =
        process.env.AGENT_HUB_TOKEN?.trim() || existingValues.AGENT_HUB_TOKEN || "";
      if (!interactive && directlyConfiguredHubToken) {
        throw new Error("AGENT_HUB_URL is required when AGENT_HUB_TOKEN is set");
      }
      values.AGENT_HUB_URL = null;
      values.AGENT_HUB_TOKEN = null;
      values.AGENT_HUB_TOKEN_KEYCHAIN_SERVICE = null;
      values.AGENT_HUB_TOKEN_KEYCHAIN_ACCOUNT = null;
      values.AGENT_HUB_TOKEN_CREDENTIAL_SERVICE = null;
      values.AGENT_HUB_TOKEN_CREDENTIAL_ACCOUNT = null;
    }
  } finally {
    terminal?.close();
  }
  values.AGENT_WORKSPACE_ROOT = workspaceRoot;
  return values;
}

function credentialReference(existingValues, kind) {
  const namespace = process.env.AGENT_CREDENTIAL_NAMESPACE?.trim() || "AgentSociety";
  const defaultAccount =
    process.env.AGENT_CREDENTIAL_ACCOUNT?.trim() || userInfo().username;
  if (kind === "model") {
    const legacyService =
      process.env.AGENT_REMOTE_API_KEY_KEYCHAIN_SERVICE?.trim() ||
      existingValues.AGENT_REMOTE_API_KEY_KEYCHAIN_SERVICE;
    const legacyAccount =
      process.env.AGENT_REMOTE_API_KEY_KEYCHAIN_ACCOUNT?.trim() ||
      existingValues.AGENT_REMOTE_API_KEY_KEYCHAIN_ACCOUNT;
    return {
      service:
        process.env.AGENT_REMOTE_API_KEY_CREDENTIAL_SERVICE?.trim() ||
        existingValues.AGENT_REMOTE_API_KEY_CREDENTIAL_SERVICE ||
        `${namespace} Remote LLM API`,
      account:
        process.env.AGENT_REMOTE_API_KEY_CREDENTIAL_ACCOUNT?.trim() ||
        existingValues.AGENT_REMOTE_API_KEY_CREDENTIAL_ACCOUNT ||
        defaultAccount,
      ...(legacyService
        ? { legacy: { service: legacyService, account: legacyAccount } }
        : {}),
    };
  }
  const legacyService =
    process.env.AGENT_HUB_TOKEN_KEYCHAIN_SERVICE?.trim() ||
    existingValues.AGENT_HUB_TOKEN_KEYCHAIN_SERVICE;
  const legacyAccount =
    process.env.AGENT_HUB_TOKEN_KEYCHAIN_ACCOUNT?.trim() ||
    existingValues.AGENT_HUB_TOKEN_KEYCHAIN_ACCOUNT;
  return {
    service:
      process.env.AGENT_HUB_TOKEN_CREDENTIAL_SERVICE?.trim() ||
      existingValues.AGENT_HUB_TOKEN_CREDENTIAL_SERVICE ||
      `${namespace} Hub`,
    account:
      process.env.AGENT_HUB_TOKEN_CREDENTIAL_ACCOUNT?.trim() ||
      existingValues.AGENT_HUB_TOKEN_CREDENTIAL_ACCOUNT ||
      defaultAccount,
    ...(legacyService
      ? { legacy: { service: legacyService, account: legacyAccount } }
      : {}),
  };
}

async function createCredentialStore() {
  let Entry;
  try {
    ({ Entry } = await import("@napi-rs/keyring"));
  } catch {
    throw new Error(
      "The native system credential store is unavailable; setup will not write secrets to a file",
    );
  }
  return {
    read(reference, label) {
      try {
        const password =
          new Entry(reference.service, reference.account).getPassword() || undefined;
        if (password || !reference.legacy) return password;
        return readLegacyCredential(reference.legacy, Entry);
      } catch {
        throw new Error(`Could not read the ${label} credential from the system store`);
      }
    },
    write(reference, secret, label) {
      try {
        new Entry(reference.service, reference.account).setPassword(secret);
      } catch {
        throw new Error(`Could not save the ${label} credential in the system store`);
      }
    },
  };
}

function readLegacyCredential(reference, Entry) {
  if (process.platform !== "darwin") {
    return new Entry(reference.service, reference.account || "").getPassword() || undefined;
  }
  const args = ["find-generic-password"];
  if (reference.account) args.push("-a", reference.account);
  args.push("-s", reference.service, "-w");
  const result = spawnSync("/usr/bin/security", args, {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  });
  return result.status === 0 ? result.stdout.trim() || undefined : undefined;
}

async function askVisible(terminal, label, current) {
  const hint = current ? ` [${current}]` : "";
  const answer = (await terminal.question(`${label}${hint}: `)).trim();
  return answer || current;
}

async function askSecret(terminal, output, label, current) {
  stdout.write(`${label}${current ? " [configured; Enter keeps it]" : ""}: `);
  output.muted = true;
  const answer = (await terminal.question("")).trim();
  output.muted = false;
  stdout.write("\n");
  return answer || current;
}

class MutedOutput extends Writable {
  muted = false;

  _write(chunk, encoding, callback) {
    if (!this.muted) stdout.write(chunk, encoding);
    callback();
  }
}

function parseEnv(text) {
  const values = {};
  for (const rawLine of text.split(/\r?\n/u)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#") || !line.includes("=")) continue;
    const separator = line.indexOf("=");
    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

function writeConfig(original, values) {
  const lines = original.split(/\r?\n/u);
  const remaining = new Map(Object.entries(values));
  const next = lines
    .map((line) => {
      const match = line.match(/^\s*([A-Z][A-Z0-9_]*)\s*=/u);
      if (!match || !remaining.has(match[1])) return line;
      const key = match[1];
      const value = remaining.get(key);
      remaining.delete(key);
      return value === null ? null : `${key}=${dotenvValue(value)}`;
    })
    .filter((line) => line !== null);
  if (remaining.size) {
    if (next.at(-1)?.trim()) next.push("");
    for (const [key, value] of remaining) {
      if (value !== null) next.push(`${key}=${dotenvValue(value)}`);
    }
  }
  const temporary = `${configPath}.${process.pid}.tmp`;
  writeFileSync(temporary, `${next.join("\n").replace(/\n+$/u, "")}\n`, {
    encoding: "utf8",
    mode: 0o600,
  });
  chmodSync(temporary, 0o600);
  renameSync(temporary, configPath);
}

function dotenvValue(value) {
  if (!value.includes('"')) return `"${value}"`;
  if (!value.includes("'")) return `'${value}'`;
  throw new Error("Configuration values cannot contain both quote styles");
}

function validateUrl(value, label) {
  let parsed;
  try {
    parsed = new URL(value);
  } catch {
    throw new Error(`${label} must be a valid URL`);
  }
  if (!["http:", "https:"].includes(parsed.protocol)) {
    throw new Error(`${label} must use HTTP or HTTPS`);
  }
}

function rejectUnsupportedEnvCharacters(label, value) {
  if (/[\r\n]/u.test(value)) throw new Error(`${label} cannot contain newlines`);
}

function looksLikePlaceholder(value) {
  return (
    value.startsWith("replace-with-") ||
    value === "your-model-id" ||
    value.includes("example.com")
  );
}

function assertNodeVersion() {
  const [major, minor] = process.versions.node.split(".").map(Number);
  if (major < 22 || (major === 22 && minor < 19)) {
    throw new Error(`Node.js 22.19 or newer is required; found ${process.versions.node}`);
  }
}

function npmCommand() {
  return process.platform === "win32" ? "npm.cmd" : "npm";
}

function run(command, args) {
  console.log(`\n> ${command} ${args.join(" ")}`);
  const result = spawnSync(command, args, {
    cwd: agentHostDir,
    env: process.env,
    stdio: "inherit",
  });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
}

main().catch((error) => {
  console.error(`\nSetup failed: ${error instanceof Error ? error.message : String(error)}`);
  process.exitCode = 1;
});
